# Site
repository:
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Roque Lopez
title: Research Engineer
email: rlopez@nyu.edu
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  roquelopez
googlescholar_username: eCBvlNMAAAAJ
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: roquelopez
xing_username:
pinterest_username:
youtube_username:
orcid_username:
medium_username:


# Additional icon links
additional_links:
#- title: Medium link
#  icon: fas fa-comments
#  url: https://medium.com/@roquelopez
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/roque_lopez.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Roque!

  I am a research engineer at New York University (NYU), I have been involved in various research and development projects throughout my career.

  Most of my background and experience is in <mark>applied machine learning</mark> and <mark>natural language processing</mark>, and I also have a interest
  in <mark>reinforcement learning</mark>.


content:
  - title: Research Software # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border:  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: BDI-Kit
        link:
        link_text:
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/VIDA-NYU/bdi-kit

        quote: 
        description: | # this will include new lines to allow paragraphs
          BDI-Kit, a Python toolkit specifically designed to streamline biomedical data integration. 
          BDI-Kit provides a suite of methods and intuitive APIs to facilitate the efficient harmonization of diverse datasets. 
          By simplifying the integration process, BDI-Kit enables practitioners and researchers to create unified datasets. 
          
          This is part of the <a href="https://vida-nyu.github.io/BDF/" target="_blank">BDF project of ARPA-H</a>.
      - layout: left
        border:  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: AlphaD3M
        link:
        link_text:
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://gitlab.com/ViDA-NYU/d3m/alphad3m

        quote: 
        description: | # this will include new lines to allow paragraphs
          AlphaD3M, an AutoML library implemented in Python that automatically synthesizes end-to-end pipelines for different machine learning tasks and different data types.
          Through an API, it allows the users to explore the input data and the derived pipelines, as well as customized the pipelines.

          This tool is part of NYU's implementation of the <a href="https://vida.engineering.nyu.edu/research/d3m//" target="_blank"> Data Driven Discovery project (D3M), DARPA</a>.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      # - layout: top
      #   title: Conferences and Journals
      - layout: top
        title:
        description: |
          Selected publications. For the complete list, please visit my <a href="https://scholar.google.com/citations?user=eCBvlNMAAAAJ" target="_blank">Google Scholar profile</a>.

      - layout: top
        title: AlphaD3M&#58; An Open-Source AutoML Library for Multiple ML Tasks
        additional_links:
          - title:  Paper
            icon: fas fa-file
            url: https://openreview.net/pdf?id=71eJdMzCCIi
          - title:  Code
            icon: fab fa-github
            url: https://gitlab.com/ViDA-NYU/d3m/alphad3m
          - title:  Video Demo
            icon: fa fa-youtube-play
            url: https://www.youtube.com/watch?v=9qJvOUOh2zM
        description: | 
          Roque Lopez, Raoni Lourenco, Remi Rampin, Sonia Castelo, Aécio Santos, Jorge Ono, Claudio Silva, Juliana Freire
          
          AutoML Conference, 2023

      - layout: top
        title: PipelineProfiler&#58; A Visual Analytics Tool for the Exploration of AutoML Pipelines
        additional_links:
          - title:  Paper
            icon: fas fa-file
            url: https://arxiv.org/pdf/2005.00160
          - title:  Code
            icon: fab fa-github
            url: https://github.com/VIDA-NYU/PipelineVis
          - title:  Video Demo
            icon: fa fa-youtube-play
            url: https://www.youtube.com/watch?v=2WSYoaxLLJ8
        description: | 
          Jorge Ono, Sonia Castelo, Roque Lopez, Enrico Bertini, Juliana Freire, Claudio Silva
          
          IEEE Visualization Conference, 2020
      
      - layout: top
        title: Opinion Summarization Methods&#58; Comparing and Extending Extractive and Abstractive Approaches
        additional_links:
          - title:  Paper
            icon: fas fa-file
            url: https://www.sciencedirect.com/science/article/abs/pii/S0957417417300829
          - title:  Code
            icon: fab fa-github
            url: https://github.com/roquelopez/opizer

        description: | 
          Roque Lopez, Thiago Pardo
          
          Expert Systems with Applications Journal, 2017

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: São Paulo University
        caption: 2013 - 2015
        sub_title: MSc in Computer Science
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Monograph title:** <a href="http://www.teses.usp.br/teses/disponiveis/55/55134/tde-07012016-114430/" target="_blank">Automatic Aspect-Based Opinion Summarization Methods</a>

          In this master’s project are presented investigations to generate extractive and abstractive summaries of opinions using an aspect-based approach. Besides using known methods in the area, it also was proposed two new methods for Portuguese language which got the best performance in the experiments.

      - layout: left
        title: San Agustin National University
        caption: 2006 - 2010
        sub_title: BSc Computer Science
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Monograph title:** <a href="/resource/RoqueLopez_BScThesis.pdf" target="_blank">Medical Documents Classification based on Keywords using Semantic Information</a>

          In this monograph, it is presented a method to classify medical documents which improves the results of Naive Bayes and Rocchio algorithm. This method, in addition to considering statistical information, taking into account the semantic relatedness between the keywords of medical documents.


  
  - title: CV
    layout: text
    content: | # this will include new lines to allow paragraphs
      You can find a detailed version of my complete CV, including additional information about my professional and research experience, by clicking 
      <a href="/resource/RoqueLopez_CV.pdf" target="_blank">here</a>.

      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
